### ISSUE TITLE
GitHub Pages?

### ISSUE THREAD

**Issue by rhlt** [Kevin4032/ProjectB#5]
**Is het een idee om GitHub Pages aan te zetten voor deze repository?**

Maandag wil ik graag aan de hand van de projectomschrijving vragen gaan stellen aan de Product Owner. Daarom had ik de vragen die we hadden ook bij de projectomschrijving gezet, die staan nu in PROJECT.md.

Het zou wel handig zijn als we die makkelijk kunnen printen of op een telefoon kunnen openen, dus zonder "GitHub" opsmuk eromheen. Dat kan met GitHub pages, maar dat moet de owner van de repository opzetten.

Ik heb zelf op mijn eigen account een een fork gemaakt van de repository, en daar Pages op aangezet. Dat ziet er dan ongeveer zo uit: [https://rhlt.github.io/ProjectB/PROJECT](https://rhlt.github.io/ProjectB/PROJECT)

Als we willen kunnen we daar zelfs een hele (statische) website op bouwen met projectinformatie, allemaal aan de hand van .md files.

**Comment by Kevin4032** [comment]
Zeker gaan we aanzetten. Ik kan niet inschatten of we dat op de main doen of een andere branch.
Wat stel je voor?

**Comment by rhlt** [comment]
Je kan het altijd nog veranderen, maar voorlopig gebruiken we het voor ons zelf, dus ik zou zeggen op develop. Op de root, zodat we de files die daar staan kunnen benaderen.

**Comment by Kevin4032** [comment]
Als het goed is staat het nu op de root in develop

**Comment by rhlt** [comment]
Dat lijkt te werken, bedankt.
[https://kevin4032.github.io/ProjectB/PROJECT](https://kevin4032.github.io/ProjectB/PROJECT)
